# Change database name, then run "rake db:create db:migrate"

defaults: &defaults
  encoding: utf-8
  username: postgres
  password: password
  pool: 5
  host: 127.0.0.1
  port: 5433
  reconnect: true
  adapter: postgresql

development:
  <<: *defaults
  database: wedding_dev

test: &test
  <<: *defaults
  database: wedding_test

cucumber:
  <<: *test
